name: "Release prep action"
description: "Run a script to update an apps toml file in preparation for a release"
outputs:
  new_version:
    description: "New version number for this release"
    value: ${{ steps.prep_step.outputs.new_version }} # 2. Map it here
runs:
  using: "composite"
  steps:
    - name: Prep release
      id: prep_step
      shell: bash
      run: |
        python "${{ github.action_path }}/release_prep.py"
